# Generated by Django 6.0.4 on 2026-05-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=45)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('technical_doc', models.FileField(upload_to='assets/docs/')),
                ('asset_image', models.ImageField(upload_to='assets/images/')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('reported_date', models.DateField()),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('report_pdf', models.FileField(upload_to='incidents/reports/')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hire_date', models.DateField()),
                ('photo', models.ImageField(upload_to='technicians/photos/')),
                ('certification', models.FileField(upload_to='technicians/certs/')),
                ('specialization', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
